//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminiotintel.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IOT_Intel_SS10Entities : DbContext
    {
        public IOT_Intel_SS10Entities()
            : base("name=IOT_Intel_SS10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_Event> Booking_Event { get; set; }
        public virtual DbSet<BookingUsers> BookingUsers { get; set; }
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<GroupUser> GroupUser { get; set; }
        public virtual DbSet<Menu_Fuctions> Menu_Fuctions { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<ResetPassUser> ResetPassUser { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_Fuctions> Users_Fuctions { get; set; }
        public virtual DbSet<Booking_Cabinet> Booking_Cabinet { get; set; }
    
        public virtual ObjectResult<GetListBookingCabinet_Result> GetListBookingCabinet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListBookingCabinet_Result>("GetListBookingCabinet");
        }
    
        public virtual ObjectResult<GetListBookingEvent_Result> GetListBookingEvent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListBookingEvent_Result>("GetListBookingEvent");
        }
    
        public virtual ObjectResult<getListBookingUser_Result> getListBookingUser(Nullable<decimal> eventID)
        {
            var eventIDParameter = eventID.HasValue ?
                new ObjectParameter("eventID", eventID) :
                new ObjectParameter("eventID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListBookingUser_Result>("getListBookingUser", eventIDParameter);
        }
    }
}
