//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminiotintel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPassUser
    {
        public decimal ResetPassID { get; set; }
        public int UserID { get; set; }
        public string PinCode { get; set; }
        public int UserCreatedID { get; set; }
        public int UserUpdatedID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
