//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminiotintel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Fuctions
    {
        public int FunctionID { get; set; }
        public int MenuID { get; set; }
        public int UserID { get; set; }
        public int GroupID { get; set; }
        public int IsView { get; set; }
        public int IsEdit { get; set; }
        public int IsDelete { get; set; }
        public int IsAddNew { get; set; }
    }
}
